/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ninja.ygor.tiads;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.google.android.gms.ads.identifier.AdvertisingIdClient;
import com.google.android.gms.ads.identifier.AdvertisingIdClient.Info;
import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.GooglePlayServicesNotAvailableException;
import com.google.android.gms.common.GooglePlayServicesRepairableException;
import com.google.android.gms.common.GooglePlayServicesUtil;
import java.io.IOException;

import android.os.AsyncTask;


@Kroll.module(name="TiAds", id="ninja.ygor.tiads")
public class TiAdsModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TiAdsModule";
	private static final boolean DBG = TiConfig.LOGD;
    boolean processed = false;
    String adidResult = "";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TiAdsModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
    
	// Get ADID - Android Advertising ID
	@Kroll.method
	public String getAdvertisingIdInfo() {
        
        if(processed) {
            return adidResult;
        }
        
        Log.d(LCAT, "Called: getAdvertisingIdInfo");
        
        AsyncTask<Void, Void, String> task = new AsyncTask<Void, Void, String>() {
           @Override
           protected String doInBackground(Void... params) {
               AdvertisingIdClient.Info idInfo = null;
               try {
                   idInfo = AdvertisingIdClient.getAdvertisingIdInfo(TiApplication.getInstance().getApplicationContext());
               } catch (GooglePlayServicesNotAvailableException e) {
                   e.printStackTrace();
               } catch (GooglePlayServicesRepairableException e) {
                   e.printStackTrace();
               } catch (Exception e) {
                   e.printStackTrace();
               }
               String advertId = null;
               try{
                   advertId = idInfo.getId();
               }catch (Exception e){
                   e.printStackTrace();
               }
               return advertId;
           }
           @Override
           protected void onPostExecute(String advertId) {
               processed = true;
               adidResult = advertId;
           }
           
       };
       task.execute();
       
       return "processing";
	}

}

